version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=Qq8MuroeWa3pHurxO94Op20nc77PqY38 #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
    volumes:
      - /data/docker/docker-vscode/data/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7564:8443
    restart: unless-stopped

